### ISSUE TITLE
Choose which builds to watch

### ISSUE THREAD

**Issue by justinabrahms** [hho/hudsonmonitor#1]
I'd like the ability to choose which builds to watch. I have about 40 builds on my hudson server, but would only like the plugin to see about 5 of them. Black list or white list works for me.

**Comment by clmbng** [comment]
i'd like the same feature. i vote for it!

**Comment by tf** [comment]
Just found out, that you can just enter the api url of a view to filter projects. Just enter:

http://hudson.yourdomain.com/view/NameOfView/api/json/

Cheers

**Comment by Steph-Fongo** [comment]
Works great. Maybe close this issue?
